### PR TITLE
Converted the MPI code to the C interface because the C++ one is no l…

### PR DESCRIPTION
**Pull request by gudlaugu**
…onger supported. Added install manifests to the CMake configuration and automatic detection of an MPI compiler. Currently no option to disable MPI support if compiler is found.

### CODE REVIEW

**Comment by henryiii** [comment]
I really appreciate your contributions. But, the expressed intention of this package is to remain source-identical with mainline ROOT Minuit 2, only changing the build system for a stand-alone one. That way, new pulls from ROOT can be made, updating this for the latest changes. These changes should probably be proposed here: https://github.com/root-project/root, and if accepted into mainline ROOT, could be included here as well.

I'm going to be contacting the maintainers of ROOT Minuit2, to see if they will accept this as an official standalone copy of Minuit2.

**Comment by gudlaugu** [comment]
No problem. I really like the availability to have Minuit2 as standalone, I was compiling the entire root package just for that. You should consider adding just the export configuration to the package for easier inclusion in other cmake projects.

**Comment by henryiii** [comment]
I'd be happy to accept a PR with changes to the CMake files, and adding export would be a useful change. I've been using this is GooFit as a subdirectory (git submodule), but the `.cmake` exports is a valid and more common way to do things.

**Comment by henryiii** [comment]
I added export/install to CMake, and just realized you had that in your PR! I should have checked before. Could you compare the two and let me know what I need to copy from this PR?

**Comment by henryiii** [comment]
Added some changes based on this PR, cherry picked a commit.

**Comment by henryiii** [comment]
Could you please remove all CMakeLists changes vs. master, and see if it still works? I think I have functionally included every change in CMakeLists (including `ENABLE_MPI`), though some in a slightly different form, and would like to make sure it all still works for you. Then this PR would only be MPI changes to source code, which could then be made to the main ROOT repo.

As a reminder, the master branch must remain without any changes to source code, since I have a script that re-syncs with ROOT master for new releases. But I can make/accept changes to CMakeLists. :)

Thanks!

**Comment by gudlaugu** [comment]
I tried your branch and it worked once I changed the following lines
install(DIRECTORY inc/Fit DESTINATION include/Minuit2)
install(DIRECTORY inc/Math DESTINATION include/Minuit2)
install(DIRECTORY inc/Minuit2 DESTINATION include/Minuit2)

**Comment by gudlaugu** [comment]
Had to make small changes in the include directories to make the directory tree in the install reasonable.

**Comment by henryiii** [comment]
Just tried an install. Wow. Fixed. 👍

**Pull request closed without merging**
